iptables -D INPUT 1
iptables -D INPUT 1
iptables -D INPUT 1
iptables -D INPUT 1
iptables -D INPUT 1
iptables -D INPUT 1
iptables -D INPUT 1
iptables -D INPUT 1
iptables -D OUTPUT 1
iptables -D OUTPUT 1
iptables -D OUTPUT 1
iptables -D OUTPUT 1
iptables -D OUTPUT 1
iptables -D OUTPUT 1
iptables -D FORWARD 1
iptables -D FORWARD 1
iptables -D FORWARD 1
iptables -D FORWARD 1
iptables -D FORWARD 1
iptables -D FORWARD 1
iptables -D FORWARD 1
iptables -D FORWARD 1
iptables -D FORWARD 1
iptables -D FORWARD 1
iptables -D FORWARD 1
iptables -D FORWARD 1
iptables -D FORWARD 1
iptables -D FORWARD 1
iptables -D FORWARD 1
iptables -D FORWARD 1

iptables -P INPUT ACCEPT
iptables -P FORWARD ACCEPT
iptables -P OUTPUT ACCEPT
